repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: golangci-lint
        name: golang linter
        entry: ./pipelines/linters/index.sh
        stages: [commit, push]
        language: golang
  - repo: local
    hooks:
      - id: tests
        name: golang tests
        entry: ./pipelines/tests/index.sh
        stages: [commit, post-commit, push]
        language: golang
  - repo: local
    hooks:
      - id: cleanup
        name: golang cleanup
        always_run: true
        entry: ./pipelines/cleanup/index.sh
        stages: [post-commit]
        language: golang