---
version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  zoo1:
    image: bitnami/zookeeper:3.8.0
    restart: always
    hostname: zoo1
    networks:
      - app-tier
    ports:
      - 22181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOO_SERVER_ID: 1
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_SERVERS: zoo1:2888:3888::1,zoo2:2888:3888::2,zoo3:2888:3888::3

  zoo2:
    image: bitnami/zookeeper:3.8.0
    restart: always
    hostname: zoo2
    networks:
      - app-tier
    ports:
      - 32181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOO_SERVER_ID: 2
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_SERVERS: zoo1:2888:3888::1,zoo2:2888:3888::2,zoo3:2888:3888::3

  zoo3:
    image: bitnami/zookeeper:3.8.0
    restart: always
    hostname: zoo3
    networks:
      - app-tier
    ports:
      - 42181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOO_SERVER_ID: 3
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_SERVERS: zoo1:2888:3888::1,zoo2:2888:3888::2,zoo3:2888:3888::3
  kafka-1:
    image: bitnami/kafka:3.0.1
    hostname: kafka-1
    networks:
      - app-tier
    ports:
      - "19092:9092"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:22181,zoo2:32181,zoo3:42181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:9092

  kafka-2:
    image: bitnami/kafka:3.0.1
    hostname: kafka-2
    networks:
      - app-tier
    ports:
      - "29092:9092"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_BROKER_ID: 2
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:22181,zoo2:32181,zoo3:42181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:9092

  kafka-3:
    image: bitnami/kafka:3.0.1
    hostname: kafka-3
    networks:
      - app-tier
    ports:
      - "39092:9092"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KAFKA_BROKER_ID: 3
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zoo1:22181,zoo2:32181,zoo3:42181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:9092