# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
# SET UP GO
trigger:
  branches:
    include:
      - master
  ## paths:

variables:
  GOBIN: "$(GOPATH)/bin" # Go binaries path
  GOROOT: "$(system.defaultWorkingDirectory)/go" # Go installation path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath" # Go workspace path
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)"
  scriptsPath: "$(system.defaultWorkingDirectory)/pipelines/" # Path to the module's code

stages:
  - stage: linter
    jobs:
      - job: TestAndBuild
        pool:
          vmImage: "ubuntu-latest"
          container: golang:1.18.4
        steps:
          - script: |
              chmod +x setup.sh
              ./setup.sh
            dispalyName: 'Setting up the needed tools'
          - script: |
              ./pipelines/linters/index.sh
            dispalyName: 'Running linters of Go'
          # - task: Go@0displayName: 'Go Test'
          #   inputs:
          #   command: 'test'
          #   arguments: './...'
          # - task: Go@0
          #   inputs:
          #     command: "build"
          #     workingDirectory: "$(System.DefaultWorkingDirectory)"
          # - task: CopyFiles@2
          #   inputs:
          #     TargetFolder: "$(Build.ArtifactStagingDirectory)"
          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     artifactName: drop
