#!/bin/sh

## TODO: Use all the modules in the workspaces
echo "Running the linters in the golang project"
golangci-lint run ./tracker/...
golangci-lint run ./replicator/...
golangci-lint run ./pkg/...
